spring:
  datasource:
    url: jdbc:h2:mem:wishlistdb # 인메모리 DB 사용
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update # 개발 단계에서는 update 또는 create 사용
    show-sql: true

  server:
    port: 8080